# set my environment
export CLICOLOR=1
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH
export EDITOR='vim'
export HISTCONTROL='erasedups:ignorespace'
export HISTIGNORE="cd ..:ls:su:sudo -s:exit"
export LSCOLORS=ExFxCxDxBxegedabagacad
export PATH="$PATH:/Users/tekniklr/bin:/opt/local/bin:/opt/local/sbin"
export PS1="\[\e[0;36m\]\u\[\e[0m\]@\[\e[0;35m\]\h\[\e[0m\]:\[\e[0;34m\]\W\[\e[0m\] \\$ "
export VIM_APP_DIR='/Applications/Programming/'
export VISUAL='vim'

# general purpose aliases
alias rake='bundle exec rake'
alias rails='bundle exec rails'
alias grep='grep --color=auto -i'
alias locate='locate -i'
alias updatedb='sudo /usr/libexec/locate.updatedb'

# directory location aliases
alias tekrails='cd /Users/tekniklr/Documents/Web/tekniklr.com/tekniklr.com'